import schema from './bot-frontmatter.schema.json';

/** JSON Schema of `BotFrontmatter`; generated by `pnpm --filter @majlis/shared gen:json-schema`, committed. */
export const botFrontmatterJsonSchema: Readonly<typeof schema> = schema;
