// The words of seed v3: what the people of Kahf Software say in their channels. Plain data, no side effects (seed-content.ts writes it).
// Authors are persona keys; `@name` in a text is a mention (seed-content.ts records the row); a line may carry reactions.

export type SeedAuthor = 'omar' | 'nadia' | 'rafi' | 'sameera' | 'tariq' | 'priya';
export type SeedEmoji = '👍' | '🎉' | '👀' | '✅' | '🔥' | '🙏' | '😄';

export interface SeedLine {
  who: SeedAuthor;
  text: string;
  /** Who reacted with what. */
  react?: [SeedEmoji, ...SeedAuthor[]][];
  /** The mention (if any) raises an unread notification for the person it names. */
  notify?: boolean;
  /** The text was edited a little after it was posted. */
  edited?: true;
  /** Marks the root of the "Deploy plan" thread (#dev), which also carries the attachment. */
  key?: 'deploy-plan';
}

const l = (who: SeedAuthor, text: string, extra: Omit<SeedLine, 'who' | 'text'> = {}): SeedLine => ({ who, text, ...extra });

// ---- Engineering ----------------------------------------------------------------------------------------------------------

export const DEPLOY_PLAN_TEXT = [
  '**Deploy plan: cache TTL 300 s to 60 s (v2.14)**',
  '',
  '1. Merge PR 482 once Rafi has reviewed it',
  '2. Deploy to staging and run the smoke suite',
  '3. Production deploy on Thursday at 10:00, canary at 10% for 30 minutes',
  '4. Rollback: `deploy rollback v2.13`; the flag `search.cache_ttl` stays reversible without a deploy',
  '',
  'Notes are in the attached PDF. Shout if something is missing.',
].join('\n');

export const DEPLOY_PLAN_REPLIES: SeedLine[] = [
  l('rafi', 'Canary at 10% for 30 minutes is fine. Who is watching the dashboards?'),
  l('nadia', 'I will, I am release owner this week. @rafi you hold the pager, right?'),
  l('rafi', 'Yes, on call until Friday 18:00. The rota is up to date.'),
  l('omar', 'One ask: write the rollback trigger down. What number makes us roll back?'),
  l('nadia', 'Error rate above 1% for 5 minutes, or p95 over 800 ms. Added to the plan.'),
  l('omar', 'Good. Also tell support before we start, they get the questions first.'),
  l('nadia', 'Will post in #support at 09:30 on Thursday.'),
  l('rafi', 'Do we need a database migration for this? I do not see one in the PR.'),
  l('nadia', 'No migration. A config flag and the TTL constant, nothing else.'),
  l('rafi', 'Then I am happy. Approving the plan from my side.'),
  l('omar', 'Approved. Thursday 10:00 it is.'),
  l('nadia', 'Thanks both. I will post status in #releases when the canary starts.'),
];

/** Lines before the Deploy plan root, then the root, then the lines after it (the last one mentions Rafi). */
export const DEV_LINES: SeedLine[] = [
  l('nadia', 'Morning all. Search results on the catalog are stale for a few minutes after an edit. Support keeps asking about it.'),
  l('rafi', 'That is the cache TTL, `search.cache_ttl` is still 300 s. We never revisited it after the catalog moved to the new indexer.'),
  l('omar', 'Is 60 s safe for the database? Last time we lowered a TTL the read replicas spiked.', { react: [['👀', 'nadia']] }),
  l('nadia', 'I measured on staging: 60 s adds about 4 queries per second at peak. Replicas barely notice.'),
  l('priya', 'Dumb question: why not invalidate on write instead of lowering the TTL?'),
  l('rafi', 'Good question, not dumb. Invalidate-on-write needs the indexer to publish events, and that is next quarter. TTL is the cheap fix now.', { react: [['👍', 'priya', 'nadia']] }),
  l('priya', 'Makes sense, thanks. I will read up on the indexer in the meantime.'),
  l('omar', 'Can someone own this? I would like it out before the end of the week.'),
  l('nadia', 'I will take it. PR today, staging tomorrow.', { react: [['🙏', 'omar']] }),
  l('rafi', 'Reminder: the rota changes on Monday. I am on the pager this week, Priya shadows.'),
  l('priya', 'Shadowing, yes. Is there a runbook I should read first?'),
  l('rafi', 'Start with the rollback runbook in `runbooks/rollback.md`. It is short, and it is the one you will need at 3 am.'),
  l('nadia', 'PR 482 is up: `search: lower cache TTL to 60 s`. Small diff, one constant and one flag.'),
  l('rafi', 'Looking now.'),
  l('rafi', 'Two comments: the flag name should follow `area.setting`, and the test should assert the TTL, not only the hit rate.'),
  l('nadia', 'Both fixed, pushed.', { edited: true }),
  l('omar', 'While we are here: the staging deploy took 14 minutes yesterday. Anybody know why?'),
  l('priya', 'I think the image layer cache was cold after the base image bump. Second run was 5 minutes.'),
  l('rafi', 'That fits. Let us pin the base image digest so it only changes when we change it.', { react: [['👍', 'omar', 'nadia']] }),
  l('omar', 'Please open a ticket for that. Not urgent.'),
  l('priya', 'Ticket opened, I will pick it up after my onboarding tasks.'),
  l('nadia', 'Staging is green. Smoke suite passed, p95 unchanged.', { react: [['🎉', 'rafi', 'omar', 'priya']] }),
  l('nadia', DEPLOY_PLAN_TEXT, { key: 'deploy-plan', react: [['👍', 'rafi', 'omar'], ['✅', 'omar']] }),
  l('priya', 'The plan reads well. One question: what is the smallest thing I can do to help on Thursday?'),
  l('rafi', 'Watch the error-rate panel next to me and tell me if it moves. It is the best way to learn the dashboards.'),
  l('omar', 'Heads-up: legal wants the data retention page reviewed before the next release. I will send it over.'),
  l('nadia', 'Fine by me, send it. Is it a doc or a PR?'),
  l('omar', 'A doc for now. Two paragraphs on log retention.'),
  l('rafi', 'Looking at alerts: the `search-p95` warning has been flapping at 790 ms. We should know why before Thursday.'),
  l('nadia', 'It is the nightly reindex. It runs at 03:00 and pushes p95 up for ten minutes. Harmless, I will move the threshold.'),
  l('rafi', 'Please do. I do not want to get paged for the reindex.'),
  l('nadia', 'Threshold moved to 900 ms for the 03:00 window.', { react: [['👍', 'rafi']] }),
  l('priya', 'I wrote up what I learned about the indexer, it is in the wiki draft. Corrections welcome.'),
  l('omar', 'Read it. Clear, and the diagram helps. Thank you, Priya.', { react: [['🙏', 'priya']] }),
  l('rafi', 'Quick one: do we still need the `legacy-search` flag? I count no readers since January.'),
  l('nadia', 'We do not. I will remove it after Thursday so there is one change at a time.'),
  l('omar', 'Agreed. One change at a time.'),
  l('priya', 'Is the canary dashboard linked from the runbook? I could not find it.'),
  l('rafi', 'It was not. Added a link under "Watching a deploy".'),
  l('nadia', '@rafi heads-up: the v2.15 canary starts next Thursday at 10:00 and you are on the pager. Can you check the rota covers Friday morning too?', { notify: true }),
];

export const GENERAL_LINES: SeedLine[] = [
  l('omar', 'Welcome to the engineering channel. Announcements go here, day-to-day questions go in #dev.'),
  l('nadia', 'Reminder that the office is closed on Monday. Deploys wait until Tuesday.'),
  l('priya', 'Hi everyone, I am Priya and I joined this week. Happy to be here!', { react: [['🎉', 'omar', 'nadia', 'rafi']] }),
  l('rafi', 'Welcome Priya. If anything about on-call confuses you, ask me.'),
  l('omar', 'Quarterly planning is next Wednesday. Please add your proposals to the planning doc by Monday evening.'),
  l('nadia', 'Added mine: search indexer events and the `legacy-search` cleanup.'),
  l('rafi', 'I added two: alert noise reduction and the on-call handover checklist.'),
  l('priya', 'Is it ok if I add something small? I would like to improve the local setup guide.'),
  l('omar', 'Yes please. A better setup guide pays back every month.', { react: [['👍', 'priya']] }),
  l('rafi', 'Lunch order for Thursday: I am collecting. Reply with your choice by 11:00.'),
  l('nadia', 'Falafel wrap for me.'),
  l('priya', 'Same, thanks!'),
  l('omar', 'Please remember to update your calendar when you are out. The rota depends on it.'),
  l('nadia', 'The laptops from the last order have arrived. They are in the cupboard by the kitchen.'),
  l('rafi', 'Security reminder: the VPN certificate renewal is next week. IT will send instructions.'),
  l('priya', 'Thanks for the tip about the shortcut keys, `j` and `k` in the thread inbox are great.'),
  l('omar', 'Friday demo at 15:00 in the big room, and on video for remote folks. Nadia is showing the search work.', { react: [['🔥', 'nadia']] }),
  l('nadia', 'I will keep it to ten minutes.'),
  l('rafi', 'Can someone bring the clicker? Mine has no battery.'),
  l('priya', 'I have one, I will bring it.'),
  l('omar', 'Thank you all for a good week. Shipping search improvements and onboarding Priya in the same week is not nothing.', { react: [['🎉', 'nadia', 'rafi', 'priya']] }),
  l('nadia', 'New hire docs: the "first week" page is updated with what Priya found missing.'),
  l('rafi', 'On-call handover is Monday 10:00. Please read the notes beforehand.'),
  l('omar', 'The planning doc is final. Search indexer events are in for next quarter.'),
  l('priya', 'Great, I am excited about that one.'),
  l('nadia', 'Reminder: expense reports are due on the 28th.'),
  l('rafi', 'If you see a red build and it is not yours, do not retry it. Tell #alerts.'),
  l('omar', 'The new keyboard layout for the meeting room TV is in the wiki.'),
  l('priya', 'Is there a place to share articles? I found a good one on caching strategies.'),
  l('omar', 'Post it here. Short summary with the link, please.'),
  l('priya', 'Done: "Caching, and when not to do it", worth fifteen minutes.', { react: [['👀', 'rafi', 'nadia']] }),
  l('rafi', 'Read it, good one. The section on stampedes is exactly our next problem.'),
  l('nadia', 'We should discuss it at the demo.'),
  l('omar', 'Added to the Friday agenda.'),
  l('nadia', 'Cake in the kitchen for Rafi\'s anniversary, three years today.', { react: [['🎉', 'omar', 'priya'], ['😄', 'rafi']] }),
  l('rafi', 'Thanks all, three years without a pager incident on a Sunday. Let me not jinx it.'),
  l('priya', 'Congratulations Rafi!'),
  l('omar', 'Have a good weekend, everyone.'),
  l('nadia', 'You too. Back Monday.'),
];

const STANDUP_YESTERDAY: Record<string, string[]> = {
  nadia: ['search cache profiling', 'PR 482 review fixes', 'staging smoke runs', 'the deploy plan', 'the indexer spike', 'cleaning flags', 'demo slides', 'the release notes', 'pairing with Priya', 'planning doc'],
  rafi: ['alert triage', 'rota changes', 'the rollback runbook', 'reviewing PR 482', 'on-call handover notes', 'noise reduction in #alerts', 'the pager test', 'a flaky test', 'dashboards for the canary', 'capacity numbers'],
  omar: ['budget review', 'hiring interviews', 'the retention page', 'planning doc', 'one-to-ones', 'the vendor contract', 'roadmap review', 'customer call', 'the board update', 'security questionnaire'],
  priya: ['onboarding tasks', 'reading the indexer code', 'the local setup guide', 'the base image ticket', 'shadowing on-call', 'the wiki draft', 'first small PR', 'the caching article', 'running the test suite', 'learning the dashboards'],
};
const STANDUP_TODAY: Record<string, string[]> = {
  nadia: ['writing the PR', 'staging deploy', 'the rollback test', 'monitoring staging', 'writing the plan', 'removing a flag', 'the Friday demo', 'canary prep', 'release notes', 'a code review'],
  rafi: ['reviewing the PR', 'updating the rota', 'testing the pager', 'writing runbook updates', 'tuning alerts', 'capacity review', 'a postmortem draft', 'on-call handover', 'watching the canary', 'noise report'],
  omar: ['sending the retention page', 'the planning meeting', 'reviewing the plan', 'a customer call', 'hiring', 'budget', 'the all-hands', 'one-to-ones', 'the vendor call', 'the demo'],
  priya: ['the setup guide', 'my first PR', 'a ticket from the board', 'shadowing Rafi', 'the wiki', 'tests for the indexer', 'the base image pin', 'reading runbooks', 'pairing with Nadia', 'the demo'],
};
/** 10 working days of standup posts, four people a day. */
export function standupLines(): SeedLine[] {
  const out: SeedLine[] = [];
  for (let day = 0; day < 10; day += 1) {
    for (const who of ['rafi', 'nadia', 'priya', 'omar'] as const) {
      const y = STANDUP_YESTERDAY[who]![day]!;
      const t = STANDUP_TODAY[who]![day]!;
      const blockers = day === 6 && who === 'priya' ? 'waiting on a laptop charger, otherwise none' : 'none';
      out.push(l(who, `**Yesterday:** ${y}. **Today:** ${t}. **Blockers:** ${blockers}.`));
    }
  }
  return out;
}

export const RELEASES_LINES: SeedLine[] = [
  l('nadia', '**v2.9.0** is out. Faster catalog imports (about 3x) and a fix for duplicate SKUs on re-import.', { react: [['🎉', 'omar', 'rafi']] }),
  l('nadia', '**v2.9.1** hotfix: the CSV export was dropping the last row when the file had no trailing newline. Fixed.'),
  l('omar', 'Thanks Nadia. Customer reports on the CSV issue should stop now.'),
  l('nadia', '**v2.10.0** is out. New: saved filters on the orders page. Improved: the export now includes timezone offsets.', { react: [['👍', 'omar']] }),
  l('nadia', '**v2.10.1**: patch for the saved filter migration on large accounts. No action needed.'),
  l('rafi', 'Deploy of v2.10.1 finished at 14:12. No alerts, error rate flat.'),
  l('nadia', '**v2.11.0** is out. Bulk edit for catalog items, up to 500 at a time. Also: keyboard shortcuts in the thread inbox.', { react: [['🔥', 'omar', 'priya']] }),
  l('rafi', 'Rollback test for v2.11.0 passed on staging: `deploy rollback v2.10.1` took 2 minutes 10 seconds.'),
  l('nadia', '**v2.11.1**: fixes a layout glitch on narrow screens and the missing tooltip on the bulk edit button.'),
  l('omar', 'Release freeze notice: no production deploys between Dec 22 and Jan 2 unless it is a security fix.'),
  l('nadia', '**v2.12.0** is out. New: webhooks for order events. Docs are in the wiki under "Webhooks".', { react: [['🎉', 'omar', 'rafi', 'priya']] }),
  l('nadia', '**v2.12.1**: webhook retries now back off exponentially. Fixes the burst we saw on Tuesday.'),
  l('rafi', 'v2.12.1 deployed, retry storms are gone from the dashboards.', { react: [['✅', 'nadia']] }),
  l('nadia', '**v2.13.0** is out. Improved search relevance for partial SKUs, plus an admin audit log page.'),
  l('nadia', '**v2.13.1**: patch for the audit log filter, which hid entries from the last hour. Fixed.'),
  l('omar', 'Please note: v2.13 includes the audit log, which customers on the Business plan have asked about for a while.'),
  l('nadia', '**v2.13.2**: security update for a dependency. Deployed at 09:40, no user impact.', { react: [['🙏', 'omar']] }),
  l('rafi', 'Deploy of v2.13.2: green. Pager quiet.'),
  l('nadia', 'Next up: **v2.14.0**, with the search cache TTL change. Deploy plan is in #dev. Thursday 10:00, canary 10%.'),
  l('omar', 'Thanks. Reminder for everyone: customer-facing announcements go through support before they go out.'),
  l('nadia', 'Canary for v2.14.0 started at 10:00. Error rate 0.2%, p95 410 ms. Watching.'),
  l('rafi', 'Pager is quiet. Dashboards look good from my side.'),
  l('nadia', 'Canary at 30 minutes, clean. Promoting to 100%.', { react: [['👍', 'rafi', 'omar']] }),
  l('nadia', '**v2.14.0** is out. Search results now refresh within a minute of a catalog edit. Thanks Rafi for the review and Priya for watching the panels.', { react: [['🎉', 'rafi', 'omar', 'priya'], ['🔥', 'rafi']] }),
  l('omar', 'Excellent work. I will tell support so they can close the open tickets about stale results.'),
  l('nadia', 'Post-release check done: error rate 0.2%, p95 405 ms, replicas fine. Closing the release.'),
  l('rafi', 'I will remove the canary dashboard filters tomorrow so they do not confuse the next person.'),
  l('nadia', 'Release notes for v2.14.0 are published in the wiki under "Releases".'),
  l('omar', 'Thank you both. Nice, boring release.'),
];

export const INCIDENTS_LINES: SeedLine[] = [
  l('rafi', '**INC-31** opened: checkout API returning 502 for about 4% of requests since 14:03.'),
  l('nadia', 'Looking at the deploy log. Nothing went out in the last two hours.'),
  l('rafi', 'Pager shows the upstream payment gateway timing out. Their status page is green.'),
  l('omar', 'I will tell support to expect questions. What is the customer impact in plain words?'),
  l('rafi', 'Some customers see "payment failed, try again" and a retry works about 90% of the time.'),
  l('omar', 'Understood, informing support now.'),
  l('nadia', 'Raised our gateway timeout from 3 s to 8 s as a stopgap. Deploying the config flag now.'),
  l('rafi', '14:31 error rate down to 0.5%. Watching.'),
  l('rafi', '14:45 error rate 0.1%. Gateway says they had a partial network issue. Resolved on their side.'),
  l('omar', 'Good. Please keep the incident open until we have the follow-ups written.'),
  l('nadia', 'Follow-ups: 1. alert on gateway latency, not only on errors. 2. retry with jitter. 3. document the timeout flag.'),
  l('rafi', 'Closing **INC-31** as resolved. Postmortem draft by Friday.', { react: [['✅', 'omar', 'nadia']] }),
  l('rafi', 'Postmortem for **INC-31** is up in the wiki. Short version: one upstream issue, we found out from errors, not latency. Fixed by alerts.'),
  l('omar', 'Thanks Rafi. Good write-up, clear actions, owners and dates.'),
  l('nadia', 'Action 1 done: alert on gateway p95 latency, warns at 1.5 s.'),
  l('nadia', 'Action 2 done: retries now use jitter. Tested on staging.'),
  l('rafi', '**INC-32** opened: dashboards show the search index 20 minutes behind.'),
  l('nadia', 'The indexer queue is backed up. A large catalog import is running.'),
  l('rafi', 'Can we pause the import? Support reports stale results for customers right now.'),
  l('nadia', 'Paused the import. Queue draining, about 1,200 items left.'),
  l('omar', 'Please tell me when it is clear. I will update the status page.'),
  l('nadia', 'Queue empty. Resuming the import with a lower batch size.'),
  l('rafi', 'Index lag back to under 10 seconds. Closing **INC-32**.', { react: [['✅', 'omar']] }),
  l('rafi', 'Cause: imports and live edits share one queue. The follow-up is to give imports their own queue. Ticket opened.'),
  l('omar', 'Good. Put it in the planning doc.'),
  l('nadia', 'Done. It is the first item under "search indexer".'),
  l('priya', 'Reading both postmortems for my onboarding, they are very clear. Can I ask why the retry change did not go through the canary?'),
  l('rafi', 'Fair question. It was a config change behind a flag and went to 10% first. We just did not announce it. Noted.'),
  l('omar', 'Let us announce flag rollouts in #releases from now on.'),
  l('nadia', 'Agreed, I will add it to the release checklist.'),
];

export const ALERTS_LINES = ((): SeedLine[] => {
  const alerts: [string, string][] = [
    ['`search-p95` WARN 810 ms (limit 800)', 'Nightly reindex window. Ignoring.'],
    ['`checkout-5xx` WARN 0.7% for 3 min', 'Gateway blip, recovered by itself.'],
    ['`ci-main` FAILED: `search/cache.test.ts` timed out', 'Flaky, retried once and it passed. Ticket open.'],
    ['`disk-db-replica-2` WARN 82% used', 'Vacuum scheduled tonight, enough headroom.'],
    ['`queue-indexer` WARN depth 4,200', 'Large import running. Watching it.'],
    ['`cert-api` INFO expires in 14 days', 'Renewal job is scheduled, nothing to do.'],
    ['`ci-main` FAILED: lint step', 'Missing semicolon in the dashboard config. Fixed in the next push.'],
    ['`checkout-5xx` WARN 1.1% for 5 min', 'Same as INC-31. Raised the gateway timeout.'],
    ['`search-p95` WARN 830 ms (limit 800)', 'Threshold moved to 900 ms for the 03:00 window.'],
    ['`db-conn-pool` WARN 88% in use', 'Normal at peak. Pool size will be reviewed next month.'],
  ];
  const out: SeedLine[] = [];
  for (let round = 0; round < 4; round += 1) {
    for (const [i, [alert, reply]] of alerts.entries()) {
      out.push(l('rafi', `**Alert** ${alert}`));
      out.push(l(((round + i) % 3 === 0 ? 'nadia' : (round + i) % 3 === 1 ? 'priya' : 'omar') as SeedAuthor, reply));
    }
  }
  // Four rounds of ten alerts and replies would be 80 lines; the channel shows the last 40.
  return out.slice(-40);
})();

export const ENG_LEADS_LINES: SeedLine[] = [
  l('omar', 'Private notes channel for leads and release owners. Compensation and hiring talk stays here.'),
  l('nadia', 'Understood. Can I ask about the open senior engineer role? We could use one more person on search.'),
  l('omar', 'Approved to open the role in Q2. I need a job description by the end of the month.'),
  l('nadia', 'I will draft it. Platform and search experience, on-call rota from month three.'),
  l('omar', 'Good. Keep the on-call expectation realistic, we had a hire leave over it last year.'),
  l('nadia', 'Understood. One week in six, shadowing first.'),
  l('omar', 'Perfect. Performance reviews open on the 1st. Please read the new template, it is shorter.'),
  l('nadia', 'Read it. The "growth" section is a clear improvement.'),
  l('omar', 'Priya\'s probation review is next month. How is she doing?'),
  l('nadia', 'Very well. She asks good questions and finishes what she starts. I would confirm early.'),
  l('omar', 'Thanks, that matches what Rafi said. I will confirm it at the one-to-one.'),
  l('nadia', 'Rafi has asked about moving to a part-time on-call lead role. Thoughts?'),
  l('omar', 'I like it. He keeps the pager sane for everyone. Let us talk to him together on Thursday.'),
  l('nadia', 'Booking a slot after standup.'),
  l('omar', 'Budget: the conference travel line is almost used. I would rather fund one person well than three poorly.'),
  l('nadia', 'Rafi for the observability conference, I think. It lines up with the alert noise work.'),
  l('omar', 'Agreed. I will approve it once he writes the proposal.'),
  l('nadia', 'Reminder to send the quarterly engineering metrics. I have the draft here.'),
  l('omar', 'Please share the draft. I want to compare it with the board update.'),
  l('nadia', 'Shared in the planning doc under "Metrics".'),
  l('omar', 'Read. Add the incident count and the mean time to recovery. The board likes numbers they can compare.'),
  l('nadia', 'Added. MTTR was 38 minutes this quarter, down from 61.'),
  l('omar', 'Good result. Thank you, and thank Rafi.'),
  l('nadia', 'I will. He wrote half the runbooks.'),
  l('omar', 'On the vendor: the monitoring contract renews in March. The price is up 12%.'),
  l('nadia', 'We use about half of it. We could go down a tier.'),
  l('omar', 'Please send me the usage numbers. I will negotiate.'),
  l('nadia', 'Will do tomorrow.'),
  l('omar', 'Last item: offsite in April. Two days, somewhere quiet. Ideas welcome.'),
  l('nadia', 'The lake house we used before. People liked the long walks.'),
  l('omar', 'I will check availability.'),
  l('nadia', 'Thanks. Anything else for this week?'),
  l('omar', 'No. Have a good weekend.'),
  l('nadia', 'You too.'),
];

// ---- Customer support -----------------------------------------------------------------------------------------------------

export const SUPPORT_LINES: SeedLine[] = [
  l('sameera', 'Good morning. Queue is at 14 open tickets, oldest is from yesterday afternoon. I will start with the oldest.'),
  l('sameera', 'Customer (Harbor & Co): "I changed a product description but the search still shows the old text." Third report this week, same cause as the others: stale search cache. Engineering has a fix planned.'),
  l('omar', 'Thanks Sameera. Please tell them it is being fixed and will be out this week. Nadia owns the change.'),
  l('sameera', 'Replied to Harbor & Co with the fix timeline. Asked them to tell me if it is not resolved by Friday.'),
  l('sameera', 'Customer (Lumen Books): cannot export orders to CSV, the file is empty. Checking.'),
  l('sameera', 'The export works when I try it with their filters. They had a date range with no orders. Explained and offered a screen share if needed.'),
  l('omar', 'Good catch. Could we show an empty-state message instead of an empty file? I will suggest it to product.', { react: [['👍', 'sameera']] }),
  l('sameera', 'That would help. I have had four tickets like it this month.'),
  l('sameera', 'Customer (Kestrel Logistics) asks whether we support single sign-on with Microsoft. They need it for a procurement review.'),
  l('omar', 'We do, in the Business plan. I will send the setup guide. Please tell them it is available.'),
  l('sameera', 'Sent. They also asked about audit logs. I told them the audit log is in the latest release.'),
  l('omar', 'Correct, v2.13. Good answer.'),
  l('sameera', 'Customer (Marlow Interiors) was charged twice for one invoice. Escalating to #escalations because I cannot see the payment gateway.'),
  l('sameera', 'Resolved: payments confirmed a duplicate authorization, not a charge. It drops off their statement in 3 days. Customer informed.'),
  l('sameera', 'A customer asked how to invite a teammate. I do not have a short answer, so I wrote one in the knowledge base. Link is in #kb-updates.'),
  l('omar', 'Thank you. These short answers save a lot of time.'),
  l('sameera', 'Mid-day update: 9 open, 3 waiting on customers, 2 waiting on engineering.'),
  l('sameera', 'Customer (Tidewater Foods): "Bulk edit is amazing, we updated 2,000 items in an afternoon." Passing it on as a win.', { react: [['🎉', 'omar']] }),
  l('omar', 'Lovely to hear. I will forward it to Nadia, she built it.'),
  l('sameera', 'Customer (Orchard Press) cannot reset a password: the email never arrives. Checked, it is in their spam folder.'),
  l('sameera', 'Asked them to allow our sender domain, and sent the reset again. Waiting for confirmation.'),
  l('sameera', 'Orchard Press confirmed, it worked. Closing.'),
  l('omar', 'Is this a common one? We might want to mention it on the sign-in page.'),
  l('sameera', 'About 3 a month. A hint on the reset screen would cut it.'),
  l('omar', 'I will raise it with product, with those numbers.'),
  l('sameera', 'End of day: 4 open, none older than a day. Quiet afternoon.'),
  l('sameera', 'Morning. Queue is at 6. Heads-up that engineering deploys on Thursday and might change search results behavior. I will watch for tickets.'),
  l('omar', 'Nadia is posting status in #releases when the canary starts. You will see it there.'),
  l('sameera', 'Great, I will keep that channel open on Thursday morning.'),
  l('sameera', 'Customer (Harbor & Co): "Search is updating quickly now, thank you." The fix landed. Closing their three tickets.', { react: [['🎉', 'omar'], ['✅', 'omar']] }),
  l('omar', 'Wonderful. Thank you for sticking with them.'),
  l('sameera', 'Customer (Birchwood Studio) wants to cancel because "it is too complicated". I offered a call to walk them through the basics.'),
  l('omar', 'Good. If they want to leave anyway, ask what we could have done better, we learn from those.'),
  l('sameera', 'They booked a call for tomorrow. I will report back.'),
  l('sameera', 'Report: the call went well. They were using the wrong import template. Fixed, they will stay.', { react: [['🙏', 'omar']] }),
  l('omar', 'A save. Please write it up in #kb-updates, other customers hit the same wall.'),
  l('sameera', 'Done, I wrote "Choosing the right import template".'),
  l('sameera', 'Customer asks for a feature: saved filters on the orders page. I told them it shipped in v2.10 and linked the guide.'),
  l('omar', 'Good. Thank you Sameera, strong week.'),
  l('sameera', 'Wrapping up. 3 open, all waiting on customers. See you Monday.'),
];

export const ENQUIRIES_LINES: SeedLine[] = [
  l('sameera', 'New enquiry from Greenfield Grocers: they run 12 stores and want to know whether we can handle several price lists per store.'),
  l('omar', 'We can, with the Business plan and customer groups. I will send the details.'),
  l('sameera', 'Sent them the pricing page and the guide on customer groups.'),
  l('sameera', 'Enquiry from a university bookstore about a non-profit discount. Do we have one?'),
  l('omar', 'Yes, 20% for registered non-profits and educational institutions. Ask them for proof and I will approve it.'),
  l('sameera', 'Asked for the registration number. Will forward when I have it.'),
  l('sameera', 'Enquiry: "Can we import products from a Google Sheet?" I told them a CSV export from the sheet works, and linked the guide.'),
  l('omar', 'Correct. We should say "Sheets" in the guide title so people find it.'),
  l('sameera', 'Good idea, I will pass it to the docs owner.'),
  l('sameera', 'Enquiry from an agency that wants to manage several client shops. Reseller program?'),
  l('omar', 'Not yet. Tell them we are working on it and ask for their use case. I will talk to them.'),
  l('sameera', 'Done, call booked with Omar on Wednesday.'),
  l('sameera', 'A very kind enquiry from someone who just wants to say thank you for the bulk edit feature. Posting it here for morale.', { react: [['🎉', 'omar']] }),
  l('sameera', 'Enquiry: GDPR data processing agreement. Where do I send people?'),
  l('omar', 'The legal page lists the DPA and the sub-processor list. I will send you the direct links.'),
  l('omar', 'Links: the DPA is under /legal/dpa and the sub-processor list under /legal/subprocessors.'),
  l('sameera', 'Saved to my replies. Thank you.'),
  l('sameera', 'Enquiry from Oakhill School: "Do you integrate with our accounting software?" Their package is not on our list.'),
  l('omar', 'Not directly. They can use the CSV export or the webhooks from v2.12. Offer to talk to their IT person.'),
  l('sameera', 'Sent. I will check back on Friday.'),
  l('sameera', 'Enquiry about uptime. Do we publish a status page?'),
  l('omar', 'Yes, the link is in the footer. We also post incident updates there.'),
  l('sameera', 'Replied with the link.'),
  l('sameera', 'Enquiry from a customer about the roadmap for mobile. I said we do not promise dates but I would pass the request on.'),
  l('omar', 'Correct. Please add them to the mobile interest list.'),
  l('sameera', 'Added.'),
  l('sameera', 'Enquiry: how long do you keep data after cancellation?'),
  l('omar', '30 days, then deleted. It is on the retention page, which I am reviewing this week.'),
  l('sameera', 'Told them 30 days and linked the page.'),
  l('omar', 'Thanks. Please check the wording again after the review.'),
  l('sameera', 'Will do.'),
];

export const ESCALATIONS_LINES: SeedLine[] = [
  l('sameera', '**Escalation**: Marlow Interiors was charged twice for one invoice. I cannot see the payment gateway. Customer is upset, ticket 4412.'),
  l('omar', 'I will check with payments. Please keep the customer updated every few hours.'),
  l('omar', 'Payments confirmed a duplicate authorization, not a second charge. It drops off in 3 days.'),
  l('sameera', 'Told the customer, with the dates. They are fine. Closing the escalation.', { react: [['✅', 'omar']] }),
  l('sameera', '**Escalation**: Kestrel Logistics asks for a security questionnaire before they sign. Deadline Friday.'),
  l('omar', 'I will take it. Please send me the file.'),
  l('sameera', 'Sent. It is 48 questions.'),
  l('omar', 'Done by Thursday evening. I will fill in what I know and ask Rafi for the infrastructure parts.'),
  l('sameera', 'Thank you. Customer is waiting, they check in on Friday.'),
  l('omar', 'Completed and sent. Please forward it to Kestrel and note the date.'),
  l('sameera', 'Forwarded. Noted in the ticket.'),
  l('sameera', '**Escalation**: a customer says an order disappeared from the list. Ticket 4437.'),
  l('omar', 'Asking engineering. Do you have the order number?'),
  l('sameera', 'It is 88142, placed Tuesday around 15:10.'),
  l('omar', 'Nadia found it. It was filtered by the saved filter bug in v2.10.0, fixed in v2.10.1. Customer needs to refresh.'),
  l('sameera', 'Told them to refresh and to clear the saved filter. Waiting on a reply.'),
  l('sameera', 'Confirmed, the order is back. Closing.'),
  l('sameera', '**Escalation**: a customer wants a refund after the 30 day window. It is a large account.'),
  l('omar', 'Policy is 30 days, but this is an account of years and the bug was ours. I approve a one-time refund.'),
  l('sameera', 'Thank you, I will process it and tell the customer it is a one-time exception.'),
  l('omar', 'Please also note the reason in the ticket for the finance team.'),
  l('sameera', 'Done.'),
  l('sameera', '**Escalation**: a customer reports they could see another customer\'s product image in a search result. Ticket 4460.'),
  l('omar', 'That is serious. I am looping in Rafi and Nadia right now. Please do not tell the customer anything yet beyond "we are looking at it".'),
  l('omar', 'Engineering found the cause: a cached thumbnail URL was reused across shops with the same SKU. Not customer data, but a wrong image. Fix is going out today.'),
  l('sameera', 'Understood. I will tell the customer it is a display issue and fixed today.'),
  l('omar', 'Please say "a cached image was shown by mistake, no data was exposed". That is accurate.'),
  l('sameera', 'Sent exactly that. Customer thanked us.'),
  l('omar', 'Good. Thank you, handled well.', { react: [['🙏', 'sameera']] }),
  l('sameera', 'Quiet week otherwise. 2 escalations open, both waiting on the customer.'),
];

export const KB_LINES: SeedLine[] = [
  l('sameera', 'New article: **How do I invite a teammate?** Short answer in three steps with a screenshot.'),
  l('omar', 'Read it. Clear. Please add "Roles explained" as a link at the end.'),
  l('sameera', 'Added.'),
  l('sameera', 'New article: **Choosing the right import template.** Three templates, when to use each.', { react: [['👍', 'omar']] }),
  l('sameera', 'Updated: **Exporting orders to CSV** now explains why a date range with no orders gives an empty file.'),
  l('omar', 'Good. Please add the same explanation to the export screen text once product has time.'),
  l('sameera', 'Noted.'),
  l('sameera', 'New article: **Setting up single sign-on with Microsoft.** Reviewed by Rafi.'),
  l('sameera', 'Updated: **Audit log** with the filters from v2.13.1.'),
  l('sameera', 'New article: **Webhooks for order events.** Includes retries and an example payload.'),
  l('omar', 'Thanks. Nadia wrote the original, please ask her to check the retry numbers.'),
  l('sameera', 'She did, one correction made: retries back off exponentially, not linearly.'),
  l('sameera', 'Retired: **Using the old search** (the page described a screen we removed in v2).'),
  l('sameera', 'New article: **My password reset email did not arrive.** Spam folder, sender domain, and the contact form as a last resort.', { react: [['🙏', 'omar']] }),
  l('sameera', 'Updated: **Refund policy** with the one-time exception rule. Reviewed by Omar.'),
  l('omar', 'Good. Do not make the exception sound like a promise.'),
  l('sameera', 'Reworded: "In some cases we can make a one-time exception."'),
  l('sameera', 'New article: **Bulk edit, up to 500 items at a time.**'),
  l('sameera', 'Updated: **Saved filters**, now with a screenshot of the new menu.'),
  l('sameera', 'Reminder: every article should end with "Was this helpful?" and a contact link. I went through the last ten and fixed three.'),
  l('omar', 'Thank you. That is the kind of hygiene that pays off.'),
  l('sameera', 'New article: **Search results look out of date.** Explains the cache and links to the release note for the fix.'),
  l('sameera', 'Updated the same article after v2.14: results now refresh within a minute.'),
  l('sameera', 'Monthly review: 6 new articles, 8 updated, 1 retired. Views are up 18%.', { react: [['🎉', 'omar']] }),
  l('omar', 'Excellent. The deflection numbers are the ones I want next month.'),
  l('sameera', 'I will add them.'),
];

// ---- Marketing ------------------------------------------------------------------------------------------------------------

export const CONTENT_LINES: SeedLine[] = [
  l('tariq', 'Content calendar for the month is in the planning doc. Two big pieces: the v2.14 launch post and a customer story with Tidewater Foods.'),
  l('priya', 'I can draft the Tidewater piece. They already said some lovely things about bulk edit.'),
  l('tariq', 'Please do. Aim for 600 words, with a quote and the numbers: 2,000 items in an afternoon.'),
  l('priya', 'On it. I will send an outline by Wednesday.'),
  l('omar', 'For the launch post: please do not promise a date for the indexer events. Say "next quarter" at most.'),
  l('tariq', 'Understood, thanks Omar.'),
  l('priya', 'Outline for the Tidewater story is up: problem, the afternoon, what changed, what is next. Comments welcome.'),
  l('tariq', 'Good bones. I would open with the afternoon, the number is the hook. Then the problem.'),
  l('priya', 'Agreed, restructured. First paragraph is now "2,000 items, one afternoon".', { react: [['👍', 'tariq']] }),
  l('tariq', 'Headline options for the v2.14 post: "Search that keeps up", "Fresh results in a minute", or "Fixing stale search".'),
  l('priya', 'I like "Search that keeps up". It says what it does, and it is not a joke at our expense.'),
  l('omar', '"Fresh results in a minute" is the most accurate. "Keeps up" promises more than 60 seconds.'),
  l('tariq', 'Fair. Going with "Fresh search results within a minute". Plain and true.', { react: [['✅', 'omar']] }),
  l('priya', 'Draft of the Tidewater story is ready for review.'),
  l('tariq', 'Reading now.'),
  l('tariq', 'Very good. Two edits: shorter intro and the quote needs a name and a role. I will ask Tidewater for permission.'),
  l('priya', 'Done, and I will remove the sentence about "game-changing". Too much.', { edited: true }),
  l('tariq', 'Permission from Tidewater received. We can use the quote and the logo.'),
  l('priya', 'Final version uploaded. Ready for scheduling.'),
  l('tariq', 'Scheduling it for Tuesday 10:00. The launch post goes out Thursday after the deploy.'),
  l('omar', 'Please confirm the Thursday post with Nadia first. If the canary fails, we do not publish.'),
  l('tariq', 'Of course. I will wait for her go.'),
  l('priya', 'Social copy for the Tidewater story: three versions in the doc. Short, medium and long.'),
  l('tariq', 'The medium one. Please add the link and the image. I will schedule it.'),
  l('priya', 'Added. The image is 1200 by 630.'),
  l('tariq', 'Scheduled for Tuesday 10:15, after the post.'),
  l('priya', 'Newsletter blurb for the launch: "Search results now refresh within a minute of an edit. Here is what changed."'),
  l('tariq', 'Add one sentence on why it matters to a shop owner: "Your customers always see the latest."'),
  l('priya', 'Added, nice.'),
  l('tariq', 'The Tidewater story is live. Early numbers are good: 340 views in the first hour.', { react: [['🎉', 'priya', 'omar']] }),
  l('priya', 'That is great. Can I share it in #general?'),
  l('tariq', 'Please do. Engineering will like seeing it.'),
  l('omar', 'Seen it, lovely work, Priya. Tidewater will too.', { react: [['🙏', 'priya']] }),
  l('tariq', 'Launch post waits for the canary. Nadia, can you confirm Thursday?'),
  l('priya', 'She posted in #releases: canary starts at 10:00 Thursday.'),
  l('tariq', 'Good. The post is scheduled for 11:00, after promotion to 100%.'),
  l('priya', 'I will proofread it once more tonight.'),
  l('tariq', 'Thank you. Last check on screenshots: use the new ones from staging, not the old ones.'),
  l('priya', 'Replaced all four.'),
  l('tariq', 'Done and scheduled. Thanks both.'),
];

export const CAMPAIGNS_LINES: SeedLine[] = [
  l('tariq', 'Q2 campaign brief is in the planning doc: "Fresh data, every time". Theme runs from April to June.'),
  l('priya', 'Read it. Is the audience small shops or the mid-size accounts?'),
  l('tariq', 'Both, with different channels: email for small shops, LinkedIn and events for mid-size.'),
  l('omar', 'Budget is approved at the number we discussed. Please track spend weekly.'),
  l('tariq', 'Will do, starting this week.'),
  l('priya', 'I made a tracking sheet with channels, spend, and leads. Link in the doc.'),
  l('tariq', 'Thanks. Add a column for cost per lead.'),
  l('priya', 'Done.'),
  l('tariq', 'Email sequence for small shops: three emails over two weeks. Drafts by Friday.'),
  l('priya', 'I will take emails 1 and 2, can you do 3?'),
  l('tariq', 'Yes, I will do 3.'),
  l('priya', 'Drafts of 1 and 2 are up for comment.'),
  l('tariq', 'Email 1 is strong. Email 2 buries the offer. Move it to the first paragraph.'),
  l('priya', 'Fixed.', { react: [['👍', 'tariq']] }),
  l('tariq', 'Email 3 is done. All three are in the sequence tool, scheduled to start Monday.'),
  l('omar', 'Please make sure the unsubscribe link works in all three. Last time it was broken in one.'),
  l('priya', 'Tested all three, links work.'),
  l('tariq', 'Webinar idea: "How shops keep catalogs fresh". 30 minutes, with a live demo of bulk edit and search.'),
  l('omar', 'Good idea. Nadia can do the demo if she has time.'),
  l('tariq', 'I will ask her. Date proposal: May 14.'),
  l('priya', 'Landing page copy for the webinar is in the doc.'),
  l('tariq', 'Good. Add speaker names once Nadia confirms.'),
  l('priya', 'Nadia confirmed in #dev, she will do the demo.'),
  l('tariq', 'Great. Registration page goes live Monday.'),
  l('priya', 'Registration page is live. 12 sign-ups after the first email.'),
  l('tariq', 'Good start. Send a reminder next Monday.'),
  l('omar', 'Weekly spend check: on budget, leads are slightly ahead of plan.'),
  l('tariq', 'Thank you. I will report the same in the leads meeting.'),
  l('priya', 'Webinar is at 62 registrations.'),
  l('tariq', 'Past our target of 50. We will cap it at 100.'),
  l('omar', 'Make sure the recording goes to the sign-ups who miss it.'),
  l('priya', 'Noted, I will add it to the follow-up email.'),
  l('tariq', 'Campaign midpoint review next Thursday. Please bring the numbers.'),
  l('priya', 'Will do.'),
];

export const BRAND_LINES: SeedLine[] = [
  l('tariq', 'Reminder of the voice: plain, specific, a little dry. We say what the product does and we do not oversell.'),
  l('priya', 'Is there a list of words we avoid?'),
  l('tariq', 'Yes: "game-changing", "revolutionary", "seamless", "unlock". It is in the style guide.'),
  l('priya', 'Found it. I will check my drafts.'),
  l('omar', 'And we do not promise dates on the roadmap. "Planned" is the strongest word.'),
  l('tariq', 'Added to the guide.'),
  l('priya', 'Question: capital T on "Team" in the product name or not?'),
  l('tariq', 'Product features are lower case, plan names are capitalized: "Business plan", "team settings".'),
  l('priya', 'Thanks, that clears it up.'),
  l('tariq', 'New logo files are in the brand folder: SVG, PNG on transparent, and a dark version.'),
  l('priya', 'Thanks. I will replace the old one on the website.'),
  l('omar', 'Please also update the email signature template.'),
  l('priya', 'Done, signatures updated.'),
  l('tariq', 'Color palette stays. One change: the accent for links is slightly darker for accessibility.'),
  l('priya', 'Contrast ratio now passes AA on white. I checked.', { react: [['👍', 'tariq']] }),
  l('tariq', 'Photography: we use real screenshots and real customers, not stock photos. If you need a photo, ask me.'),
  l('priya', 'Understood.'),
  l('tariq', 'The new boilerplate paragraph for press: "Kahf Software builds tools for shops that sell online. Teams use manythreads to talk, decide and ship together."'),
  l('omar', 'Good. Please remove "decide" so it does not suggest an approval product.'),
  l('tariq', 'Fair, changed to "talk and ship together".'),
  l('priya', 'Template for case studies is ready in the brand folder.'),
  l('tariq', 'Used it for Tidewater, works well.'),
  l('priya', 'I updated the slide template with the new logo.'),
  l('tariq', 'Thank you. Everyone should use it from the next presentation.'),
  l('omar', 'Noted for the all-hands.'),
  l('tariq', 'Reminder: brand questions go here, not by direct message. Others learn from the answers.'),
  l('priya', 'Good rule.'),
  l('tariq', 'One more: product screenshots use the demo workspace "Kahf Software", never real customer data.'),
  l('priya', 'Of course.'),
  l('tariq', 'Quarterly brand check next month. I will post the checklist.'),
];

export const SOCIAL_LINES: SeedLine[] = [
  l('tariq', 'Posting schedule for the week: Mon customer story, Wed tip of the week, Fri release note.'),
  l('priya', 'I can draft Wednesday\'s tip. Idea: "Use j and k to move through your thread inbox".'),
  l('tariq', 'Nice and specific. A short clip would help.'),
  l('priya', 'I will record a 10 second screen capture.'),
  l('priya', 'Clip ready, 9 seconds, no sound.'),
  l('tariq', 'Looks good. Add captions for people who scroll with the sound off.'),
  l('priya', 'Captions added.'),
  l('tariq', 'Scheduled for Wednesday 12:00.'),
  l('tariq', 'Monday post performed well: 2,100 impressions, 4.1% engagement.'),
  l('priya', 'The quote card did better than the link. We should do more of those.'),
  l('tariq', 'Agreed. Three quote cards for next week, from the customer stories.'),
  l('priya', 'I will make them. Using the brand template.'),
  l('omar', 'Please do not quote customers on social without permission, even if the quote is already on the site.'),
  l('tariq', 'We always ask. Tidewater said yes in writing.'),
  l('priya', 'Cards ready, all with permission logged in the sheet.'),
  l('tariq', 'Thanks. Schedule them Mon, Tue, Thu.'),
  l('priya', 'Scheduled.'),
  l('tariq', 'A customer posted a nice comment about bulk edit on LinkedIn. Reposting with thanks.'),
  l('priya', 'I answered the question under the post about the 500 item limit.'),
  l('tariq', 'Good. Fast and friendly answers matter more than the posts.'),
  l('priya', 'Weekly numbers: 8,400 impressions, 3.6% engagement, 31 new followers.'),
  l('omar', 'Good trend. Please keep an eye on the cost of the paid test.'),
  l('tariq', 'The paid test ends Friday. I will report.'),
  l('priya', 'Friday release post drafted: "v2.14, fresh search results within a minute".'),
  l('tariq', 'Wait for the canary, as always.'),
  l('priya', 'Of course. Holding until Nadia confirms.'),
  l('tariq', 'Posted. First reactions are positive.', { react: [['🎉', 'priya', 'omar']] }),
  l('priya', 'Replied to the first three comments.'),
  l('tariq', 'Thank you. Good week.'),
];

export const ANALYTICS_LINES: SeedLine[] = [
  l('tariq', 'Weekly numbers: 12,400 visits, 3.4% sign-up rate, 420 new sign-ups.'),
  l('priya', 'Is the sign-up rate up or down from last week?'),
  l('tariq', 'Up from 3.1%. The new landing page helps.', { react: [['🎉', 'priya']] }),
  l('priya', 'Do we know which source drives the most sign-ups?'),
  l('tariq', 'Email at 38%, organic search at 27%, social at 11%, the rest direct and referral.'),
  l('omar', 'Please separate paid from organic next time. I want to see what the budget buys.'),
  l('tariq', 'Will do. Splitting the report from this week.'),
  l('priya', 'I added a "paid vs organic" tab to the dashboard.'),
  l('tariq', 'Thanks. Paid: 62 sign-ups for 1,800 spent, about 29 per sign-up.'),
  l('omar', 'That is within what we expected. Organic is what pays for itself.'),
  l('tariq', 'Webinar funnel: 62 registered, 41 attended, 9 asked for a call.'),
  l('priya', 'Nine calls is a great outcome. I will make a follow-up list.'),
  l('tariq', 'Please do. Sameera can help with the call scheduling.'),
  l('priya', 'Asked her. She can take three a day.'),
  l('tariq', 'Customer story: 340 views in the first hour, 1,900 after a day, 14 sign-ups attributed.'),
  l('omar', 'Good result for the effort. Do we have a number for read time?'),
  l('priya', 'Average read time 3 min 10 s. 62% scrolled to the quote.'),
  l('tariq', 'Strong. More of these.'),
  l('priya', 'Bounce rate on the pricing page is high at 71%. Might be worth a test.'),
  l('tariq', 'Let us test a shorter plan comparison. I will brief a test for next sprint.'),
  l('omar', 'Please keep tests to one change at a time, so we can read the result.'),
  l('tariq', 'Of course.'),
  l('priya', 'Newsletter: 41% open rate, 6% click rate. The subject with a number did best.'),
  l('tariq', 'Noted. Numbers in subject lines from now on.'),
  l('priya', 'Monthly report is in the folder, summary in the first page.'),
  l('omar', 'Read it, thank you. Clear and short.'),
  l('tariq', 'Next month: conversion by plan and churn by source.'),
  l('priya', 'I will start collecting the data now.'),
  l('tariq', 'Thanks, Priya. Great work on the dashboards.', { react: [['🙏', 'priya']] }),
];

/** A short conversation between Nadia and Rafi; the last line, Rafi's question, is unread for Nadia. */
export const DM_LINES: SeedLine[] = [
  l('nadia', 'Hey, are you on the pager this week?'),
  l('rafi', 'Yes, until Friday 18:00. Priya is shadowing.'),
  l('nadia', 'Nice. I will need you at the canary on Thursday, 10:00.'),
  l('rafi', 'Already in my calendar.'),
  l('nadia', 'Thanks! Also, can you look at my PR before standup?'),
  l('rafi', 'Will do.'),
  l('rafi', 'Check the rota?'),
];

/** Lines of the load-test channel are generated in SQL; this is the shape of one. */
export const LOAD_TEST_COUNT = 5000;
